master-data:
  bank-accounts:
  - 14131050002359
  - 14111060000068
  bank-filters:
  - None
  - BdREN
  - Software
  modes:
  - Cash
  - Cheque
  - Bank
  months:
  - Jan21.
  - Feb21.
  - Mar21.
  - Apr21.
  - May21.
  - Jun21.
  wings:
  - Acquisition
  - Delivery
  - Operations
selection:
  selected-account: '14111060000068'
  selected-filter: None
  selected-mode: Cash
  selected-month: May21.
  selected-reference: 21/867
  selected-wing: Operations
