master-data:
  bank-accounts:
  - 14131050002359
  - 14111060000068
  bank-filters:
  - None
  - BdREN
  - Software
  modes:
  - Cash
  - Cheque
  - Bank
  months:
  - Apr20
  - May20
  - Jun20
  - Jul20
  wings:
  - Acquisition
  - Delivery
  - Operations
selection:
  selected-account: '14111060000068'
  selected-filter: None
  selected-mode: Bank
  selected-month: May20
  selected-reference: 20/764
  selected-wing: Operations
